//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportApp.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImportApp.WPF.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentExcelFile.
        /// </summary>
        internal static string CurrentExcelFile {
            get {
                return ResourceManager.GetString("CurrentExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentExcelSheet.
        /// </summary>
        internal static string CurrentExcelSheet {
            get {
                return ResourceManager.GetString("CurrentExcelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ServerItem/Database.
        /// </summary>
        internal static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ServerItem/DataSource.
        /// </summary>
        internal static string DataSourcePath {
            get {
                return ResourceManager.GetString("DataSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultSubcategory.
        /// </summary>
        internal static string DefaultSubcategory {
            get {
                return ResourceManager.GetString("DefaultSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        internal static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article with same name already exist..
        /// </summary>
        internal static string DuplicateArticle {
            get {
                return ResourceManager.GetString("DuplicateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with same name already exist..
        /// </summary>
        internal static string DuplicateCategory {
            get {
                return ResourceManager.GetString("DuplicateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount with same name already exist..
        /// </summary>
        internal static string DuplicateDiscount {
            get {
                return ResourceManager.GetString("DuplicateDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier with same name already exist..
        /// </summary>
        internal static string DuplicatedSupplier {
            get {
                return ResourceManager.GetString("DuplicatedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage with same name already exist..
        /// </summary>
        internal static string DuplicateStorage {
            get {
                return ResourceManager.GetString("DuplicateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory with same name already exist..
        /// </summary>
        internal static string DuplicateSubcategory {
            get {
                return ResourceManager.GetString("DuplicateSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000-0000-0000-0000-000000000000.
        /// </summary>
        internal static string EmptyGuid {
            get {
                return ResourceManager.GetString("EmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Encrypt=False.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Try again..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not import an empty list of items..
        /// </summary>
        internal static string ImportException {
            get {
                return ResourceManager.GetString("ImportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create button disabled. No categories in DB..
        /// </summary>
        internal static string NoCategories {
            get {
                return ResourceManager.GetString("NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create button disabled. No storages was found in DB..
        /// </summary>
        internal static string NoStorages {
            get {
                return ResourceManager.GetString("NoStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create button disabled. No SubCategories in DB..
        /// </summary>
        internal static string NoSubcategories {
            get {
                return ResourceManager.GetString("NoSubcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Worksheets|*.xls;*.xlsx;*.xlsm.
        /// </summary>
        internal static string OpenDialogFilter {
            get {
                return ResourceManager.GetString("OpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Excel file.
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ServerItem/Port.
        /// </summary>
        internal static string PortPath {
            get {
                return ResourceManager.GetString("PortPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local\POSSector\DatabaseSettings.xml.
        /// </summary>
        internal static string POSFolderPath {
            get {
                return ResourceManager.GetString("POSFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file is successfully selected..
        /// </summary>
        internal static string SelectedExcelFile {
            get {
                return ResourceManager.GetString("SelectedExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t select sheet without selecting file first..
        /// </summary>
        internal static string SelectSheetError {
            get {
                return ResourceManager.GetString("SelectSheetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ServerItem/FullServerName.
        /// </summary>
        internal static string ServerInstancePath {
            get {
                return ResourceManager.GetString("ServerInstancePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, you have to set files at Settings page..
        /// </summary>
        internal static string SettingsError {
            get {
                return ResourceManager.GetString("SettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel sheet selected successfully..
        /// </summary>
        internal static string SheetSelectedSuccessfully {
            get {
                return ResourceManager.GetString("SheetSelectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storages.
        /// </summary>
        internal static string Storages {
            get {
                return ResourceManager.GetString("Storages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successfully executed. .
        /// </summary>
        internal static string SuccessImport {
            get {
                return ResourceManager.GetString("SuccessImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file successfully updated..
        /// </summary>
        internal static string UpdatedExcelFile {
            get {
                return ResourceManager.GetString("UpdatedExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just selected same file as current..
        /// </summary>
        internal static string UpdatedSameFile {
            get {
                return ResourceManager.GetString("UpdatedSameFile", resourceCulture);
            }
        }
    }
}
